# Generated by Django 5.1.7 on 2025-04-15 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendID', models.AutoField(primary_key=True, serialize=False)),
                ('studentNumber', models.CharField(max_length=9)),
                ('subjectCode', models.CharField(max_length=20)),
                ('dateAndTime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('D_Code', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('D_Name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('staffNumber', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentNumber', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('logID', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=255)),
                ('logDescription', models.CharField(max_length=255)),
                ('dateAndTime', models.DateTimeField(auto_now=True)),
                ('logDetails', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessmentCode', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('assessmentName', models.CharField(max_length=225)),
                ('totalMark', models.IntegerField()),
                ('staffNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='FaceRecognition',
            fields=[
                ('faceRecognitionID', models.AutoField(primary_key=True, serialize=False)),
                ('faceImg', models.CharField(max_length=220)),
                ('studentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('studentMarkID', models.AutoField(primary_key=True, serialize=False)),
                ('marksObtained', models.IntegerField()),
                ('assessmentCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.assessment')),
                ('studentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectCode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=100)),
                ('D_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('studentProgressID', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=20)),
                ('studentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
                ('subjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerCourses',
            fields=[
                ('lecturerCourseID', models.AutoField(primary_key=True, serialize=False)),
                ('staffNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.lecturer')),
                ('subjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.subject')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='subjectCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.subject'),
        ),
    ]
