# Generated by Django 5.1.7 on 2025-04-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='studentNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subjectCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.subject'),
        ),
    ]
