# Generated by Django 5.1.7 on 2025-05-13 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_attendance_studentnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='studentNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subjectCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.subject'),
        ),
    ]
