# Generated by Django 5.1.7 on 2025-05-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_lecturer_user_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
