# Generated by Django 5.1.7 on 2025-05-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_student_user'),
        ('webapp', '0006_assessment_due_date'),
    ]

    operations = [
    ]
